import type { OpeningWeakToStrongRules } from './openingWeakToStrongTypes'

export const OPENING_WEAK_TO_STRONG_RULE_VERSION = 'opening-weak-to-strong.v1'

export const DEFAULT_OPENING_WEAK_TO_STRONG_RULES: OpeningWeakToStrongRules = {
  auctionTrendStart: '09:20:00',
  initialBaselineStart: '09:20:00',
  initialBaselineEnd: '09:20:30',
  auctionStart: '09:24:50',
  auctionEnd: '09:25:10',
  detectStart: '09:30:00',
  detectEnd: '09:35:00',
  auctionWeakMaxPct: 0.5,
  auctionGapJumpMinPctPoint: 3,
  auctionGapFirstWindowMinPct: 1.5,
  lowOpenRedJumpMinPctPoint: 1.5,
  lowOpenRedFirstWindowMinPct: 1,
  strongOpenFirstWindowMinPct: 3,
  nearLimitDistancePct: 2,
  minCurrentAmount: 30_000_000,
  minAmountDelta: 20_000_000,
  openingLiquidityMinAmount: 5_000_000,
  auctionLateLiftStart: '09:24:00',
  auctionLateLiftTotalMinPctPoint: 1,
  auctionLateLiftLateMinPctPoint: 0.5,
  auctionPriceLiftMinPctPoint: 0.8,
  auctionAmountLiftMinRatio: 0.35,
  auctionLatePriceLiftMinPctPoint: 0.3,
  auctionLateAmountLiftMinRatio: 0.2,
  auctionLateLiftFinalMinPct: 0,
  auctionLateLiftAmountDeltaMin: 8_000_000,
  auctionLateLiftLateAmountDeltaMin: 5_000_000,
  auctionLateLiftFirstWindowMinPct: 2.5,
  auctionLateLiftJumpMinPctPoint: 2,
  auctionLateHighRetreatPctPoint: 0.2,
  previousWeakScoreMin: 30,
  minAuctionCoverageRatio: 0.95,
  maxQuoteAgeMs: 30_000,
  minCurrentVolume: 1_000_000,
  openingSupportOpenRatio: 0.995,
  auctionGapMaxScore: 40,
  auctionGapScoreSlope: 4,
  auctionGapOpenStrengthScore: 15,
  auctionGapAmountStrongScore: 20,
  auctionGapAmountWeakScore: 10,
  auctionGapQualityGoodScore: 8,
  auctionGapQualityDegradedScore: 3,
  auctionLateLiftCoreScore: 25,
  auctionLateLiftAmountRatioScore: 18,
  auctionLateLiftOpenStrengthScore: 18,
  strongOpenNearLimitScore: 25,
  strongOpenOpenStrengthScore: 25,
  lowOpenRedReversalScore: 22,
  lowOpenTurnRedScore: 10,
  previousWeakContextScore: 8,
}
