// @ts-nocheck
// src/config/algorithms.ts
// 所有算法定义和配置

import type { Algorithm } from '@/types'
import { BREATH_FACTOR_IDS } from '@/types'

// ========== 阶段权重乘数配置 ==========
export const PHASE_MULTIPLIERS = {
  冰点期: {
    contrarian: 2.5,
    breathZtCount: 2.0,
    breathDtCount: 2.0,
    continuousDays: 0.6,
    zlje: 0.5,
    themeHeat: 0.5,
    themeMomentum: 0.5,
  },
  启动期: {
    themeHeat: 1.8,
    themeMomentum: 1.3,
    breathPassRate: 1.8,
    compRank: 1.3,
    breathZtCount: 1.3,
    zlje: 1.2,
    continuousDays: 1.2,
  },
  发酵期: {
    themeMomentum: 1.8,
    themeHeat: 1.4,
    zlje: 1.5,
    breathMaxDays: 1.5,
    breathPassRate: 1.3,
    continuousDays: 1.3,
    breathZtCount: 1.2,
  },
  高潮期: {
    continuousDays: 1.8,
    zlje: 1.6,
    breathMaxDays: 1.6,
    breathZhabanRate: 0.4,
    contrarian: 0.3,
    breathZtCount: 1.2,
    themeMomentum: 1.3,
    turnover: 1.4,
    turnoverRate: 1.2,
    breathPassRate: 1.2,
  },
  退潮期: {
    continuousDays: 0.4,
    zlje: 0.3,
    themeHeat: 0.4,
    themeMomentum: 0.4,
    contrarian: 1.2,
    breathDtCount: 1.8,
    breathZhabanRate: 1.3,
    breathZtCount: 0.6,
    breathPassRate: 0.5,
    breathMaxDays: 0.5,
  },
  震荡期: {
    themeHeat: 1.0,
    themeMomentum: 1.0,
    breathZtCount: 1.0,
    breathDtCount: 1.0,
    continuousDays: 1.0,
    zlje: 1.0,
    compRank: 1.0,
  },
} as const

export type MarketPhase = keyof typeof PHASE_MULTIPLIERS

// ========== 默认阈值配置 ==========
export const DEFAULT_THRESHOLDS = {
  totalLeader: 80,
  sectorLeader: 65,
  continuousLeader: 70,
  middleLeader: 60,
  emotionLeader: 55,
}

// ========== 算法定义 ==========
export const ALGORITHMS: Record<string, Algorithm> = {
  balanced: {
    id: 'balanced',
    name: '平衡型',
    icon: '⚖️',
    description: '综合排名优先，兼顾技术指标和市场情绪',
    category: 'comprehensive',
    color: '#3498db',
    phaseMultipliers: PHASE_MULTIPLIERS,
    factors: {
      compRank: { weight: 0.15, enabled: true, min: 0.1, max: 0.4 },
      change: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      turnover: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      turnoverRate: { weight: 0.06, enabled: true, min: 0.03, max: 0.15 },
      zlje: { weight: 0.1, enabled: true, min: 0.05, max: 0.25 },
      themeHeat: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      themeMomentum: { weight: 0.06, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.PHASE]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.ZT_COUNT]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.DT_COUNT]: { weight: 0.04, enabled: true, min: 0.02, max: 0.08 },
      [BREATH_FACTOR_IDS.ZHABAN_RATE]: { weight: 0.04, enabled: true, min: 0.02, max: 0.1 },
      [BREATH_FACTOR_IDS.FENGBAN_RATE]: { weight: 0.04, enabled: true, min: 0.02, max: 0.1 },
      [BREATH_FACTOR_IDS.PASS_RATE]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.MAX_DAYS]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.UP_DOWN_RATIO]: { weight: 0.03, enabled: true, min: 0.01, max: 0.06 },
      [BREATH_FACTOR_IDS.EMOTION_VALUE]: { weight: 0.02, enabled: true, min: 0.01, max: 0.05 },
      [BREATH_FACTOR_IDS.MARKET_SCORE]: { weight: 0.02, enabled: true, min: 0.01, max: 0.05 },
      contrarian: { weight: 0.05, enabled: true, min: 0.03, max: 0.12 },
    },
    leaderThresholds: {
      total: { minScore: 80 },
      sector: { minScore: 65 },
      continuous: { minScore: 70 },
      middle: { minScore: 60 },
      emotion: { minScore: 55 },
    },
  },

  dragonFirst: {
    id: 'dragonFirst',
    name: '龙头优先',
    icon: '👑',
    description: '强调市场地位和资金关注，结合市场情绪',
    category: 'leader',
    color: '#FFD700',
    phaseMultipliers: PHASE_MULTIPLIERS,
    factors: {
      compRank: { weight: 0.12, enabled: true, min: 0.05, max: 0.25 },
      marketCap: { weight: 0.1, enabled: true, min: 0.05, max: 0.25 },
      zlje: { weight: 0.12, enabled: true, min: 0.05, max: 0.25 },
      turnover: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      continuousDays: { weight: 0.1, enabled: true, min: 0.05, max: 0.2 },
      themeHeat: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      themeMomentum: { weight: 0.06, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.PHASE]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.ZT_COUNT]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.PASS_RATE]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.MAX_DAYS]: { weight: 0.1, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.UP_DOWN_RATIO]: { weight: 0.04, enabled: true, min: 0.02, max: 0.08 },
      contrarian: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
    },
    leaderThresholds: {
      total: { minScore: 85 },
      sector: { minScore: 70 },
      continuous: { minScore: 75 },
      middle: { minScore: 65 },
      emotion: { minScore: 60 },
    },
  },

  moneyDriven: {
    id: 'moneyDriven',
    name: '资金驱动',
    icon: '💰',
    description: '主力资金流向优先，结合市场情绪',
    category: 'money',
    color: '#2ed573',
    phaseMultipliers: PHASE_MULTIPLIERS,
    factors: {
      zlje: { weight: 0.2, enabled: true, min: 0.1, max: 0.4 },
      zljzb: { weight: 0.12, enabled: true, min: 0.05, max: 0.25 },
      turnover: { weight: 0.12, enabled: true, min: 0.05, max: 0.25 },
      change: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      compRank: { weight: 0.08, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.PHASE]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.ZT_COUNT]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.DT_COUNT]: { weight: 0.05, enabled: true, min: 0.02, max: 0.1 },
      [BREATH_FACTOR_IDS.PASS_RATE]: { weight: 0.06, enabled: true, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.MAX_DAYS]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      contrarian: { weight: 0.05, enabled: true, min: 0.02, max: 0.1 },
    },
    leaderThresholds: {
      total: { minScore: 80 },
      sector: { minScore: 65 },
      continuous: { minScore: 70 },
      middle: { minScore: 60 },
      emotion: { minScore: 55 },
    },
  },

  sentimentDriven: {
    id: 'sentimentDriven',
    name: '情绪驱动',
    icon: '🔥',
    description: '市场情绪优先，捕捉情绪龙头',
    category: 'sentiment',
    color: '#ff7f50',
    phaseMultipliers: PHASE_MULTIPLIERS,
    factors: {
      [BREATH_FACTOR_IDS.PHASE]: { weight: 0.15, enabled: true, min: 0.08, max: 0.25 },
      [BREATH_FACTOR_IDS.ZT_COUNT]: { weight: 0.12, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.DT_COUNT]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.ZHABAN_RATE]: { weight: 0.1, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.FENGBAN_RATE]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      [BREATH_FACTOR_IDS.PASS_RATE]: { weight: 0.12, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.MAX_DAYS]: { weight: 0.1, enabled: true, min: 0.05, max: 0.2 },
      [BREATH_FACTOR_IDS.UP_DOWN_RATIO]: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
      contrarian: { weight: 0.08, enabled: true, min: 0.03, max: 0.15 },
    },
    leaderThresholds: DEFAULT_THRESHOLDS,
  },

  ml: {
    id: 'ml',
    name: '机器学习',
    icon: '🤖',
    description: '动态权重，自适应优化',
    category: 'ml',
    color: '#9b59b6',
    phaseMultipliers: PHASE_MULTIPLIERS,
    factors: {
      compRank: { weight: 'dynamic', enabled: true, baseWeight: 0.06, min: 0.03, max: 0.12 },
      change: { weight: 'dynamic', enabled: true, baseWeight: 0.05, min: 0.03, max: 0.1 },
      zlje: { weight: 'dynamic', enabled: true, baseWeight: 0.06, min: 0.03, max: 0.12 },
      themeHeat: { weight: 'dynamic', enabled: true, baseWeight: 0.06, min: 0.03, max: 0.12 },
      themeMomentum: { weight: 'dynamic', enabled: true, baseWeight: 0.05, min: 0.03, max: 0.1 },
      [BREATH_FACTOR_IDS.PHASE]: { weight: 'dynamic', enabled: true, baseWeight: 0.08, min: 0.04, max: 0.15 },
      [BREATH_FACTOR_IDS.ZT_COUNT]: { weight: 'dynamic', enabled: true, baseWeight: 0.06, min: 0.03, max: 0.12 },
      [BREATH_FACTOR_IDS.MAX_DAYS]: { weight: 'dynamic', enabled: true, baseWeight: 0.07, min: 0.03, max: 0.14 },
      contrarian: { weight: 'dynamic', enabled: true, baseWeight: 0.06, min: 0.03, max: 0.12 },
    },
    adaptive: true,
    learningRate: 0.05,
    leaderThresholds: DEFAULT_THRESHOLDS,
  },
}
