-- QuantBoard Supabase schema.
-- This file intentionally matches quant-board/backend/data/models.py.
-- Run it in Supabase SQL Editor after backing up any existing cloud data.

begin;

drop table if exists snapshot_sector_rows cascade;
drop table if exists snapshot_stock_rows cascade;
drop table if exists snapshot_frames cascade;
drop table if exists snapshot_records cascade;
drop table if exists snapshots cascade;
drop table if exists sync_outbox cascade;
drop table if exists golden_ranktrend_cases cascade;
drop table if exists optimization_runs cascade;
drop table if exists backtest_runs cascade;
drop table if exists datasets cascade;

create table datasets (
  id varchar(64) primary key,
  name varchar(160) not null,
  source_type varchar(32) not null,
  source_path text not null default '',
  db_name varchar(80) not null default 'DragonBoardData',
  schema_fingerprint varchar(96) not null default '',
  snapshot_count integer not null default 0,
  frame_count integer not null default 0,
  stock_row_count integer not null default 0,
  sector_row_count integer not null default 0,
  start_date varchar(16),
  end_date varchar(16),
  snapshot_types_json text not null default '[]',
  metadata_json text not null default '{}',
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table snapshot_records (
  id bigint generated by default as identity primary key,
  dataset_id varchar(64) not null references datasets(id) on delete cascade,
  snapshot_id varchar(160) not null,
  type varchar(32) not null,
  trading_date varchar(16) not null,
  slot_time varchar(16) not null default '',
  timestamp bigint not null,
  display_key varchar(160) not null default '',
  capture_mode varchar(32) not null default 'real_time',
  source varchar(32) not null default 'browser_runtime',
  payload_json text not null default '{}',
  unique (dataset_id, snapshot_id)
);

create table snapshot_frames (
  id bigint generated by default as identity primary key,
  dataset_id varchar(64) not null references datasets(id) on delete cascade,
  snapshot_id varchar(160) not null,
  type varchar(32) not null,
  trading_date varchar(16) not null,
  slot_time varchar(16) not null default '',
  timestamp bigint not null,
  capture_mode varchar(32) not null default 'real_time',
  source varchar(32) not null default 'browser_runtime',
  market_context_json text not null default '{}',
  stock_row_count integer not null default 0,
  sector_row_count integer not null default 0,
  unique (dataset_id, snapshot_id)
);

create table snapshot_stock_rows (
  id bigint generated by default as identity primary key,
  dataset_id varchar(64) not null references datasets(id) on delete cascade,
  row_id varchar(220) not null,
  snapshot_id varchar(160) not null,
  type varchar(32) not null,
  trading_date varchar(16) not null,
  slot_time varchar(16) not null default '',
  timestamp bigint not null,
  capture_mode varchar(32) not null default 'real_time',
  code varchar(16) not null,
  name varchar(80) not null default '',
  rank integer not null default 0,
  price double precision,
  change double precision,
  volume_ratio double precision,
  zlje double precision,
  zljzb double precision,
  turnover double precision,
  turnover_rate double precision,
  payload_json text not null default '{}',
  unique (dataset_id, row_id)
);

create table snapshot_sector_rows (
  id bigint generated by default as identity primary key,
  dataset_id varchar(64) not null references datasets(id) on delete cascade,
  row_id varchar(240) not null,
  snapshot_id varchar(160) not null,
  type varchar(32) not null,
  trading_date varchar(16) not null,
  slot_time varchar(16) not null default '',
  timestamp bigint not null,
  entity_type varchar(40) not null default '',
  entity_key varchar(160) not null default '',
  entity_name varchar(160) not null default '',
  rank integer not null default 0,
  payload_json text not null default '{}',
  unique (dataset_id, row_id)
);

create table golden_ranktrend_cases (
  id varchar(64) primary key,
  name varchar(160) not null,
  dataset_id varchar(64),
  input_json text not null default '{}',
  expected_json text not null default '{}',
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table backtest_runs (
  id varchar(64) primary key,
  dataset_id varchar(64) not null,
  strategy_name varchar(80) not null default 'rank_trend_candidate',
  strategy_version varchar(40) not null default '0.1.0',
  snapshot_type varchar(32) not null default 'half_hour',
  config_hash varchar(96) not null default '',
  random_seed integer not null default 0,
  status varchar(32) not null default 'completed',
  request_json text not null default '{}',
  result_json text not null default '{}',
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table optimization_runs (
  id varchar(64) primary key,
  dataset_id varchar(64) not null,
  strategy_name varchar(80) not null default 'rank_trend_candidate',
  method varchar(40) not null default 'grid',
  config_hash varchar(96) not null default '',
  random_seed integer not null default 0,
  status varchar(32) not null default 'completed',
  request_json text not null default '{}',
  result_json text not null default '{}',
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table sync_outbox (
  id bigint generated by default as identity primary key,
  op_type varchar(80) not null,
  dataset_id varchar(64),
  snapshot_id varchar(160),
  payload_json text not null default '{}',
  idempotency_key varchar(160) not null unique,
  status varchar(24) not null default 'pending',
  retry_count integer not null default 0,
  last_error text,
  next_retry_at timestamp without time zone,
  created_at timestamp without time zone not null default (now() at time zone 'utc'),
  updated_at timestamp without time zone not null default (now() at time zone 'utc')
);

create index ix_snapshot_records_dataset_id on snapshot_records(dataset_id);
create index ix_snapshot_records_snapshot_id on snapshot_records(snapshot_id);
create index ix_snapshot_records_timestamp on snapshot_records(timestamp);
create index ix_snapshot_records_trading_date on snapshot_records(trading_date);
create index ix_snapshot_records_type on snapshot_records(type);

create index ix_snapshot_frames_dataset_id on snapshot_frames(dataset_id);
create index ix_snapshot_frames_snapshot_id on snapshot_frames(snapshot_id);
create index ix_snapshot_frames_timestamp on snapshot_frames(timestamp);
create index ix_snapshot_frames_trading_date on snapshot_frames(trading_date);
create index ix_snapshot_frames_type on snapshot_frames(type);

create index ix_snapshot_stock_rows_code on snapshot_stock_rows(code);
create index ix_snapshot_stock_rows_dataset_id on snapshot_stock_rows(dataset_id);
create index ix_snapshot_stock_rows_row_id on snapshot_stock_rows(row_id);
create index ix_snapshot_stock_rows_snapshot_id on snapshot_stock_rows(snapshot_id);
create index ix_snapshot_stock_rows_timestamp on snapshot_stock_rows(timestamp);
create index ix_snapshot_stock_rows_trading_date on snapshot_stock_rows(trading_date);
create index ix_snapshot_stock_rows_type on snapshot_stock_rows(type);

create index ix_snapshot_sector_rows_dataset_id on snapshot_sector_rows(dataset_id);
create index ix_snapshot_sector_rows_row_id on snapshot_sector_rows(row_id);
create index ix_snapshot_sector_rows_snapshot_id on snapshot_sector_rows(snapshot_id);
create index ix_snapshot_sector_rows_timestamp on snapshot_sector_rows(timestamp);
create index ix_snapshot_sector_rows_trading_date on snapshot_sector_rows(trading_date);
create index ix_snapshot_sector_rows_type on snapshot_sector_rows(type);

create index ix_backtest_runs_dataset_id on backtest_runs(dataset_id);
create index ix_optimization_runs_dataset_id on optimization_runs(dataset_id);

create index ix_sync_outbox_dataset_id on sync_outbox(dataset_id);
create index ix_sync_outbox_op_type on sync_outbox(op_type);
create index ix_sync_outbox_snapshot_id on sync_outbox(snapshot_id);
create index ix_sync_outbox_status on sync_outbox(status);
create index ix_sync_outbox_status_next_retry_at on sync_outbox(status, next_retry_at);

commit;

notify pgrst, 'reload schema';
