import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, test } from 'vitest'

const panelPath = () => join(process.cwd(), 'src', 'components', 'panels', 'CandidatePoolPanel.vue')
const panelSource = () => readFileSync(panelPath(), 'utf8')
const appSource = () => readFileSync(join(process.cwd(), 'src', 'App.vue'), 'utf8')

describe('CandidatePoolPanel source contract', () => {
  test('provides a candidate workbench backed by the candidate journal service', () => {
    expect(existsSync(panelPath())).toBe(true)
    const source = panelSource()

    expect(source).toContain('候选池')
    expect(source).toMatch(/candidateJournalService\.listCandidates/)
    expect(source).toMatch(/candidateJournalService\.updateCandidateStatus/)
    expect(source).toContain('入池理由')
    expect(source).toContain('交易假设')
    expect(source).toContain('失效条件')
    expect(source).toContain('规则分析')
    expect(source).toContain('今日新增')
    expect(source).toContain('平均评分')
    expect(source).toContain('当前重分析')
    expect(source).toContain('入池快照')
    expect(source).toContain('假设编辑')
    expect(source).toContain('写回当前分析')
    expect(source).toContain('复盘闭环')
    expect(source).toContain('触发率')
    expect(source).toContain('失效率')
    expect(source).toContain('title="复盘胜率"')
    expect(source).toMatch(/stateLabel/)
    expect(source).toMatch(/candidateJournalService\.reanalyzeCandidate/)
    expect(source).toMatch(/candidateJournalService\.updateCandidateThesis/)
    expect(source).toMatch(/candidateJournalService\.writeBackCurrentAnalysis/)
    expect(source).toMatch(/candidateJournalService\.saveCandidateReview/)
    expect(source).toMatch(/const\s+candidateStats\s*=\s*computed/)
    expect(source).toMatch(/const\s+selectedReview\s*=\s*computed/)
    expect(source).toMatch(/const\s+thesisForm\s*=\s*ref/)
    expect(source).toMatch(/const\s+reviewForm\s*=\s*ref/)
    expect(source).toContain('候选状态更新失败')
    expect(source).toMatch(/async function updateStatus\(status: CandidateStatus\)/)
    expect(source).toMatch(/try\s*\{\s*const updated = await candidateJournalService\.updateCandidateStatus/)
  })

  test('registers the candidate pool panel in App without replacing favorites', () => {
    const source = appSource()

    expect(source).toMatch(/CandidatePoolPanel/)
    expect(source).toMatch(/candidatePool:\s*false/)
    expect(source).toMatch(/<CandidatePoolPanel\s+v-model:visible="panels\.candidatePool"/)
    expect(source).toContain("'candidate-pool:open'")
    expect(source).toContain('候选池')
    expect(source).toMatch(/<FavoritePanel\s+v-model:visible="panels\.favorite"/)
    expect(source).toContain("'rank-trend:open'")
    expect(source).toMatch(/<RankTrendPanel\s+:visible="panels\.rankTrend"/)
  })

  test('clears status filters before opening a candidate from the quote table', () => {
    const source = panelSource()

    expect(source).toMatch(/async function openCandidate\(target: \{ candidateId\?: string; stockCode\?: string \} = \{\}\)/)
    expect(source).toMatch(/const hasTarget = !!\(target\.candidateId \|\| target\.stockCode\)/)
    expect(source).toMatch(/statusFilter\.value = ''/)
    expect(source).toMatch(/await loadCandidates\(\)/)
    expect(source).toMatch(/if \(hasTarget && !matched\)/)
  })

  test('exposes phase 10 candidate operations and list controls', () => {
    const source = panelSource()

    expect(source).toContain('删除候选')
    expect(source).toContain('加入自选')
    expect(source).toContain('股票详情')
    expect(source).toContain('排名趋势')
    expect(source).toContain('评分排序')
    expect(source).toContain('风险筛选')
    expect(source).toContain('题材筛选')
    expect(source).toMatch(/candidateJournalService\.deleteCandidate/)
    expect(source).toMatch(/candidateJournalService\.addCandidateToFavorites/)
    expect(source).toMatch(/EventManager\.emit\('stock:show-detail'/)
    expect(source).toMatch(/EventManager\.emit\('rank-trend:open'/)
    expect(source).toMatch(/const\s+visibleCandidates\s*=\s*computed/)
    expect(source).toMatch(/function candidateThemeText/)
  })

  test('exposes phase 11 candidate quality statistics instead of trade PnL metrics', () => {
    const source = panelSource()

    expect(source).toContain('候选漏斗')
    expect(source).toContain('质量拆解')
    expect(source).toContain('复盘结果')
    expect(source).toContain('命中率')
    expect(source).toContain('平均跟踪')
    expect(source).toMatch(/buildCandidateQualityStats/)
    expect(source).toMatch(/qualityStats\.value\.breakdowns\.themes/)
    expect(source).toMatch(/qualityStats\.value\.breakdowns\.rankTrendTiers/)
    expect(source).toMatch(/qualityStats\.value\.breakdowns\.grades/)
    expect(source).toMatch(/qualityStats\.value\.breakdowns\.moneyFlowStates/)
    expect(source).toMatch(/qualitySummary\.themes/)
    expect(source).toMatch(/qualitySummary\.rankTrend/)
    expect(source).toMatch(/qualitySummary\.grades/)
    expect(source).toMatch(/qualitySummary\.moneyFlow/)
    expect(source).toContain('候选研究，不含交易盈亏')
  })

  test('keeps the candidate workbench layout as left list and right detail container', () => {
    const source = panelSource()
    const bodyIndex = source.indexOf('<div class="candidate-body">')
    const listIndex = source.indexOf('<aside class="candidate-list">')
    const detailIndex = source.indexOf('<main class="candidate-detail">')
    const qualityIndex = source.indexOf('<section class="quality-dashboard')

    expect(bodyIndex).toBeGreaterThan(0)
    expect(listIndex).toBeGreaterThan(bodyIndex)
    expect(detailIndex).toBeGreaterThan(listIndex)
    expect(qualityIndex).toBeGreaterThan(detailIndex)
    expect(source.indexOf('<section class="quality-dashboard')).toBe(source.lastIndexOf('<section class="quality-dashboard'))
  })

  test('orders the right detail area as a candidate decision workflow with auxiliary dashboards aside', () => {
    const source = panelSource()
    const detailIndex = source.indexOf('<main class="candidate-detail">')
    const workflowIndex = source.indexOf('<div class="candidate-workflow">')
    const decisionIndex = source.indexOf('当前决策')
    const analysisIndex = source.indexOf('规则分析', decisionIndex)
    const thesisIndex = source.indexOf('假设编辑', analysisIndex)
    const reviewIndex = source.indexOf('复盘闭环', thesisIndex)
    const sideBriefIndex = source.indexOf('<aside class="candidate-side-brief">')
    const discoveryIndex = source.indexOf('建议入池')
    const qualityIndex = source.indexOf('候选质量')

    expect(workflowIndex).toBeGreaterThan(detailIndex)
    expect(decisionIndex).toBeGreaterThan(workflowIndex)
    expect(analysisIndex).toBeGreaterThan(decisionIndex)
    expect(thesisIndex).toBeGreaterThan(analysisIndex)
    expect(reviewIndex).toBeGreaterThan(thesisIndex)
    expect(sideBriefIndex).toBeGreaterThan(workflowIndex)
    expect(discoveryIndex).toBeGreaterThan(sideBriefIndex)
    expect(qualityIndex).toBeGreaterThan(discoveryIndex)
  })

  test('exposes phase 12 structured rule evidence, penalties and condition groups in the right detail area', () => {
    const source = panelSource()
    const detailIndex = source.indexOf('<main class="candidate-detail">')
    const evidenceIndex = source.indexOf('证据项')
    const conditionIndex = source.indexOf('结构化条件')

    expect(evidenceIndex).toBeGreaterThan(detailIndex)
    expect(conditionIndex).toBeGreaterThan(detailIndex)
    expect(source).toContain('扣分项')
    expect(source).toContain('触发条件')
    expect(source).toContain('买入前提')
    expect(source).toContain('失效条件')
    expect(source).toContain('结构化风险')
    expect(source).toMatch(/currentAnalysis\.evidence/)
    expect(source).toMatch(/currentAnalysis\.penalties/)
    expect(source).toMatch(/currentAnalysis\.structuredThesis\.triggerConditions/)
    expect(source).toMatch(/currentAnalysis\.structuredThesis\.entryPrerequisites/)
    expect(source).toMatch(/currentAnalysis\.structuredThesis\.invalidationConditions/)
    expect(source).toMatch(/currentAnalysis\.structuredRisks/)
  })

  test('exposes phase 13 manual-confirm discovery recommendations without changing the left-right layout', () => {
    const source = panelSource()
    const bodyIndex = source.indexOf('<div class="candidate-body">')
    const detailIndex = source.indexOf('<main class="candidate-detail">')
    const discoveryIndex = source.indexOf('建议入池')

    expect(source).toMatch(/candidateDiscoveryService\.discover/)
    expect(source).toContain('刷新建议')
    expect(source).toContain('人工确认后入池')
    expect(source).toContain('重复候选')
    expect(source).toContain('预期跟踪')
    expect(source).toMatch(/confirmDiscoveryRecommendation/)
    expect(source).toMatch(/candidateJournalService\.addCandidateFromStock/)
    expect(discoveryIndex).toBeGreaterThan(detailIndex)
    expect(detailIndex).toBeGreaterThan(bodyIndex)
  })

  test('uses dashboard-grade visual affordances for the candidate pool surface', () => {
    const source = panelSource()

    expect(source).toContain('class="candidate-item-main"')
    expect(source).toContain('class="candidate-status"')
    expect(source).toContain('class="candidate-score"')
    expect(source).toContain('class="quality-block"')
    expect(source).toContain('--candidate-accent')
    expect(source).toMatch(/\.candidate-item\.active::before/)
    expect(source).toMatch(/:focus-visible/)
    expect(source).toMatch(/@media\s*\(max-width:\s*900px\)/)
  })

  test('uses high-contrast financial typography and color tokens', () => {
    const source = panelSource()

    expect(source).toContain('--candidate-font-data')
    expect(source).toContain('--candidate-bg: #111318')
    expect(source).toContain('--candidate-surface: #1b2028')
    expect(source).toContain('--candidate-text: #f4f7fb')
    expect(source).toContain('--candidate-accent: #ffb13b')
    expect(source).toMatch(/font-family:\s*var\(--candidate-font-ui\)/)
    expect(source).toMatch(/font-family:\s*var\(--candidate-font-data\)/)
    expect(source).toMatch(/\.stat-card::before/)
  })
})
